name: Auto Format Code w/ Black

on: push

jobs:
  format:
    name: Format code w/ Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: black .

      - name: Check for changes
        id: check_changes
        run: |
          git add .
          if git diff --staged --exit-code; then
            echo "No changes found."
            exit 0
          else
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git commit -m "Auto-format code with black" || true
            exit 0
          fi

      - name: Push changes
        if: steps.check_changes.outputs.exit_code == '0'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
